### ISSUE TITLE
recipe for target 'vmlinux' failed

### ISSUE THREAD

**Issue by zgangguoguo** [Panchajanya1999/msm-4.14#15]
system:ubuntu 18.04.6
`# bash kernel.sh`
Spent a long time at` LTO vmlinux.o`
error.log
>make[1]: Entering directory '/home/gynl/Desktop/kernel/msm-4.14/out'
  GEN     ./Makefile
scripts/kconfig/conf  --silentoldconfig Kconfig
  CHK     include/config/kernel.release
  GEN     ./Makefile
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  Using .. as source for kernel
  CHK     scripts/mod/devicetable-offsets.h
  CHK     include/generated/timeconst.h
  CHK     include/generated/bounds.h
  CHK     include/generated/asm-offsets.h
  CALL    ../scripts/checksyscalls.sh
  CHK     include/generated/compile.h
  CHK     kernel/config_data.h
  DTC     arch/arm64/boot/dts/xiaomi/violet-sm6150.dtb
  DTC     arch/arm64/boot/dts/xiaomi/violet-sm6150-overlay.dtbo
  GEN     .version
  CHK     include/generated/compile.h
  UPD     include/generated/compile.h
  CC      init/version.o
  AR      init/built-in.o
  AR      built-in.o
  LTO     vmlinux.o
../scripts/link-vmlinux.sh: line 102: 24613 Killed                  ${LD} ${LDFLAGS} -r -o ${1} $(lto_lds) ${objects}
/home/gynl/Desktop/kernel/msm-4.14/Makefile:1198: recipe for target 'vmlinux' failed
make[1]: *** [vmlinux] Error 137
make[1]: Target '_all' not remade because of errors.
make[1]: Leaving directory '/home/gynl/Desktop/kernel/msm-4.14/out'
Makefile:146: recipe for target 'sub-make' failed
make: *** [sub-make] Error 2
make: Target '_all' not remade because of errors.

**Comment by Panchajanya1999** [comment]
Yeah, that's normal. You can turn off LTO from defconfig.

**Comment by zgangguoguo** [comment]
thank you for your reply.
in `violet-perf_defconfig`

> `CONFIG_LTO=y`

> `CONFIG_ARCH_SUPPORTS_LTO_CLANG=y`

> `CONFIG_LTO_CLANG=y`

Which should I modify?

**Comment by zgangguoguo** [comment]
I have compiled successfully, thank you for your help
