### ISSUE TITLE
Kernel Flashing Failed

### ISSUE THREAD

**Issue by Z3wn** [Panchajanya1999/msm-4.14#4]
Flashing failed. It says
`No ramdisk found to unpack. Aborting...`
I tried it on Redmi Note 7 pro(violet) miui 12 Global Rom.

**Comment by Panchajanya1999** [comment]
Which build you tried ?

**Comment by Z3wn** [comment]
I tried Latest build from Team420.
Please take a little look.
![Screenshot_2020-12-09-03-59-26](https://user-images.githubusercontent.com/59116834/101661342-8e20d380-3a76-11eb-8dbb-93a479bae199.png)

**Comment by karthik558** [comment]
Flash magisk and flash kernel ,and one more thing its not azure , its nethunter kernel based on Azure..

**Comment by Z3wn** [comment]
@karthik558 I tried that too. It did boot to system. It stuck on boot logo.

**Comment by karthik558** [comment]
@Z3wn its not azure , so better u report that issue on nethunter group / repository....
