### ISSUE TITLE
Compile faild caused by cpumask

### ISSUE THREAD

**Issue by zixijian** [Panchajanya1999/msm-4.14#6]
```
7pro:~/r# ./run.sh
make[1]: Entering directory '/root/r/out'
  GEN     ./Makefile
#
# configuration written to .config
#
make[1]: Leaving directory '/root/r/out'
make[1]: Entering directory '/root/r/out'
  GEN     ./Makefile
scripts/kconfig/conf  --silentoldconfig Kconfig
  CHK     include/config/kernel.release
  GEN     ./Makefile
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  Using .. as source for kernel
  CHK     scripts/mod/devicetable-offsets.h
  CHK     include/generated/timeconst.h
  CHK     include/generated/bounds.h
  CHK     include/generated/asm-offsets.h
  CALL    ../scripts/checksyscalls.sh
  CHK     include/generated/compile.h
  CHK     kernel/config_data.h
  AS      arch/arm64/lib/clear_page.o
  AS      arch/arm64/lib/clear_user.o
  AS      arch/arm64/lib/copy_from_user.o
  AS      arch/arm64/lib/copy_in_user.o
  AS      arch/arm64/lib/copy_page.o
  CC      drivers/char/adsprpc.o
  AS      arch/arm64/lib/copy_to_user.o
  CC      arch/arm64/lib/csum.o
  CC      arch/arm64/lib/delay.o
../drivers/char/adsprpc.c:3483:3: error: no member named 'counter' in 'struct cpumask'
                atomic_set(&fl->pm_qos_req.cpus_affine, *cpumask_bits(cpu_lp_mask));
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../arch/arm64/include/asm/atomic.h:57:44: note: expanded from macro 'atomic_set'
#define atomic_set(v, i)                WRITE_ONCE(((v)->counter), (i))
                                        ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
../include/linux/compiler.h:270:17: note: expanded from macro 'WRITE_ONCE'
        union { typeof(x) __val; char __c[1]; } __u =   \
                       ^
../drivers/char/adsprpc.c:3483:3: error: no member named 'counter' in 'struct cpumask'
                atomic_set(&fl->pm_qos_req.cpus_affine, *cpumask_bits(cpu_lp_mask));
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../arch/arm64/include/asm/atomic.h:57:44: note: expanded from macro 'atomic_set'
#define atomic_set(v, i)                WRITE_ONCE(((v)->counter), (i))
                                        ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
../include/linux/compiler.h:271:30: note: expanded from macro 'WRITE_ONCE'
                { .__val = (__force typeof(x)) (val) }; \
                                           ^
../drivers/char/adsprpc.c:3483:3: error: no member named 'counter' in 'struct cpumask'
                atomic_set(&fl->pm_qos_req.cpus_affine, *cpumask_bits(cpu_lp_mask));
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../arch/arm64/include/asm/atomic.h:57:44: note: expanded from macro 'atomic_set'
#define atomic_set(v, i)                WRITE_ONCE(((v)->counter), (i))
                                        ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
../include/linux/compiler.h:272:22: note: expanded from macro 'WRITE_ONCE'
        __write_once_size(&(x), __u.__c, sizeof(x));    \
                            ^
../drivers/char/adsprpc.c:3483:3: error: no member named 'counter' in 'struct cpumask'
                atomic_set(&fl->pm_qos_req.cpus_affine, *cpumask_bits(cpu_lp_mask));
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../arch/arm64/include/asm/atomic.h:57:44: note: expanded from macro 'atomic_set'
#define atomic_set(v, i)                WRITE_ONCE(((v)->counter), (i))
                                        ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
../include/linux/compiler.h:272:42: note: expanded from macro 'WRITE_ONCE'
        __write_once_size(&(x), __u.__c, sizeof(x));    \
                                                ^
../drivers/char/adsprpc.c:3966:39: warning: implicit conversion from 'unsigned long long' to 'unsigned int' changes value from 18446744073709551615 to 4294967295 [-Wconstant-conversion]
        dma_set_max_seg_size(sess->smmu.dev, DMA_BIT_MASK(32));
        ~~~~~~~~~~~~~~~~~~~~                 ^~~~~~~~~~~~~~~~
../include/linux/dma-mapping.h:196:40: note: expanded from macro 'DMA_BIT_MASK'
#define DMA_BIT_MASK(n) (((n) == 64) ? ~0ULL : ((1ULL<<(n))-1))
                                       ^~~~~
../drivers/char/adsprpc.c:3967:54: warning: shift count >= width of type [-Wshift-count-overflow]
        dma_set_seg_boundary(sess->smmu.dev, (unsigned long)DMA_BIT_MASK(64));
                                                            ^~~~~~~~~~~~~~~~
../include/linux/dma-mapping.h:196:54: note: expanded from macro 'DMA_BIT_MASK'
#define DMA_BIT_MASK(n) (((n) == 64) ? ~0ULL : ((1ULL<<(n))-1))
                                                     ^ ~~~
../drivers/char/adsprpc.c:4104:40: warning: implicit conversion from 'unsigned long long' to 'unsigned int' changes value from 18446744073709551615 to 4294967295 [-Wconstant-conversion]
                dma_set_max_seg_size(sess->smmu.dev, DMA_BIT_MASK(32));
                ~~~~~~~~~~~~~~~~~~~~                 ^~~~~~~~~~~~~~~~
../include/linux/dma-mapping.h:196:40: note: expanded from macro 'DMA_BIT_MASK'
#define DMA_BIT_MASK(n) (((n) == 64) ? ~0ULL : ((1ULL<<(n))-1))
                                       ^~~~~
../drivers/char/adsprpc.c:4106:21: warning: shift count >= width of type [-Wshift-count-overflow]
                                        (unsigned long)DMA_BIT_MASK(64));
                                                       ^~~~~~~~~~~~~~~~
../include/linux/dma-mapping.h:196:54: note: expanded from macro 'DMA_BIT_MASK'
#define DMA_BIT_MASK(n) (((n) == 64) ? ~0ULL : ((1ULL<<(n))-1))
                                                     ^ ~~~
4 warnings and 4 errors generated.
../scripts/Makefile.build:361: recipe for target 'drivers/char/adsprpc.o' failed
make[3]: *** [drivers/char/adsprpc.o] Error 1
../scripts/Makefile.build:676: recipe for target 'drivers/char' failed
make[2]: *** [drivers/char] Error 2
/root/r/Makefile:1206: recipe for target 'drivers' failed
make[1]: *** [drivers] Error 2
make[1]: *** Waiting for unfinished jobs....
  AS      arch/arm64/lib/memchr.o
  AS      arch/arm64/lib/memcmp.o
  AS      arch/arm64/lib/memcpy.o
  AS      arch/arm64/lib/memmove.o
  AS      arch/arm64/lib/memset.o
  AS      arch/arm64/lib/strchr.o
  AS      arch/arm64/lib/strcmp.o
  AS      arch/arm64/lib/strlen.o
  AS      arch/arm64/lib/strncmp.o
  AS      arch/arm64/lib/strnlen.o
  AS      arch/arm64/lib/strrchr.o
  AS      arch/arm64/lib/tishift.o
  AR      arch/arm64/lib/lib.a
  EXPORTS arch/arm64/lib/lib-ksyms.o
  AR      arch/arm64/lib/built-in.o
make[1]: Leaving directory '/root/r/out'
Makefile:146: recipe for target 'sub-make' failed
make: *** [sub-make] Error 2
```

**Comment by Panchajanya1999** [comment]
@

> ```
> 7pro:~/r# ./run.sh
> make[1]: Entering directory '/root/r/out'
>   GEN     ./Makefile
> #
> # configuration written to .config
> #
> make[1]: Leaving directory '/root/r/out'
> make[1]: Entering directory '/root/r/out'
>   GEN     ./Makefile
> scripts/kconfig/conf  --silentoldconfig Kconfig
>   CHK     include/config/kernel.release
>   GEN     ./Makefile
>   CHK     include/generated/uapi/linux/version.h
>   CHK     include/generated/utsrelease.h
>   Using .. as source for kernel
>   CHK     scripts/mod/devicetable-offsets.h
>   CHK     include/generated/timeconst.h
>   CHK     include/generated/bounds.h
>   CHK     include/generated/asm-offsets.h
>   CALL    ../scripts/checksyscalls.sh
>   CHK     include/generated/compile.h
>   CHK     kernel/config_data.h
>   AS      arch/arm64/lib/clear_page.o
>   AS      arch/arm64/lib/clear_user.o
>   AS      arch/arm64/lib/copy_from_user.o
>   AS      arch/arm64/lib/copy_in_user.o
>   AS      arch/arm64/lib/copy_page.o
>   CC      drivers/char/adsprpc.o
>   AS      arch/arm64/lib/copy_to_user.o
>   CC      arch/arm64/lib/csum.o
>   CC      arch/arm64/lib/delay.o
> ../drivers/char/adsprpc.c:3483:3: error: no member named 'counter' in 'struct cpumask'
>                 atomic_set(&fl->pm_qos_req.cpus_affine, *cpumask_bits(cpu_lp_mask));
>                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../arch/arm64/include/asm/atomic.h:57:44: note: expanded from macro 'atomic_set'
> #define atomic_set(v, i)                WRITE_ONCE(((v)->counter), (i))
>                                         ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
> ../include/linux/compiler.h:270:17: note: expanded from macro 'WRITE_ONCE'
>         union { typeof(x) __val; char __c[1]; } __u =   \
>                        ^
> ../drivers/char/adsprpc.c:3483:3: error: no member named 'counter' in 'struct cpumask'
>                 atomic_set(&fl->pm_qos_req.cpus_affine, *cpumask_bits(cpu_lp_mask));
>                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../arch/arm64/include/asm/atomic.h:57:44: note: expanded from macro 'atomic_set'
> #define atomic_set(v, i)                WRITE_ONCE(((v)->counter), (i))
>                                         ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
> ../include/linux/compiler.h:271:30: note: expanded from macro 'WRITE_ONCE'
>                 { .__val = (__force typeof(x)) (val) }; \
>                                            ^
> ../drivers/char/adsprpc.c:3483:3: error: no member named 'counter' in 'struct cpumask'
>                 atomic_set(&fl->pm_qos_req.cpus_affine, *cpumask_bits(cpu_lp_mask));
>                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../arch/arm64/include/asm/atomic.h:57:44: note: expanded from macro 'atomic_set'
> #define atomic_set(v, i)                WRITE_ONCE(((v)->counter), (i))
>                                         ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
> ../include/linux/compiler.h:272:22: note: expanded from macro 'WRITE_ONCE'
>         __write_once_size(&(x), __u.__c, sizeof(x));    \
>                             ^
> ../drivers/char/adsprpc.c:3483:3: error: no member named 'counter' in 'struct cpumask'
>                 atomic_set(&fl->pm_qos_req.cpus_affine, *cpumask_bits(cpu_lp_mask));
>                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../arch/arm64/include/asm/atomic.h:57:44: note: expanded from macro 'atomic_set'
> #define atomic_set(v, i)                WRITE_ONCE(((v)->counter), (i))
>                                         ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
> ../include/linux/compiler.h:272:42: note: expanded from macro 'WRITE_ONCE'
>         __write_once_size(&(x), __u.__c, sizeof(x));    \
>                                                 ^
> ../drivers/char/adsprpc.c:3966:39: warning: implicit conversion from 'unsigned long long' to 'unsigned int' changes value from 18446744073709551615 to 4294967295 [-Wconstant-conversion]
>         dma_set_max_seg_size(sess->smmu.dev, DMA_BIT_MASK(32));
>         ~~~~~~~~~~~~~~~~~~~~                 ^~~~~~~~~~~~~~~~
> ../include/linux/dma-mapping.h:196:40: note: expanded from macro 'DMA_BIT_MASK'
> #define DMA_BIT_MASK(n) (((n) == 64) ? ~0ULL : ((1ULL<<(n))-1))
>                                        ^~~~~
> ../drivers/char/adsprpc.c:3967:54: warning: shift count >= width of type [-Wshift-count-overflow]
>         dma_set_seg_boundary(sess->smmu.dev, (unsigned long)DMA_BIT_MASK(64));
>                                                             ^~~~~~~~~~~~~~~~
> ../include/linux/dma-mapping.h:196:54: note: expanded from macro 'DMA_BIT_MASK'
> #define DMA_BIT_MASK(n) (((n) == 64) ? ~0ULL : ((1ULL<<(n))-1))
>                                                      ^ ~~~
> ../drivers/char/adsprpc.c:4104:40: warning: implicit conversion from 'unsigned long long' to 'unsigned int' changes value from 18446744073709551615 to 4294967295 [-Wconstant-conversion]
>                 dma_set_max_seg_size(sess->smmu.dev, DMA_BIT_MASK(32));
>                 ~~~~~~~~~~~~~~~~~~~~                 ^~~~~~~~~~~~~~~~
> ../include/linux/dma-mapping.h:196:40: note: expanded from macro 'DMA_BIT_MASK'
> #define DMA_BIT_MASK(n) (((n) == 64) ? ~0ULL : ((1ULL<<(n))-1))
>                                        ^~~~~
> ../drivers/char/adsprpc.c:4106:21: warning: shift count >= width of type [-Wshift-count-overflow]
>                                         (unsigned long)DMA_BIT_MASK(64));
>                                                        ^~~~~~~~~~~~~~~~
> ../include/linux/dma-mapping.h:196:54: note: expanded from macro 'DMA_BIT_MASK'
> #define DMA_BIT_MASK(n) (((n) == 64) ? ~0ULL : ((1ULL<<(n))-1))
>                                                      ^ ~~~
> 4 warnings and 4 errors generated.
> ../scripts/Makefile.build:361: recipe for target 'drivers/char/adsprpc.o' failed
> make[3]: *** [drivers/char/adsprpc.o] Error 1
> ../scripts/Makefile.build:676: recipe for target 'drivers/char' failed
> make[2]: *** [drivers/char] Error 2
> /root/r/Makefile:1206: recipe for target 'drivers' failed
> make[1]: *** [drivers] Error 2
> make[1]: *** Waiting for unfinished jobs....
>   AS      arch/arm64/lib/memchr.o
>   AS      arch/arm64/lib/memcmp.o
>   AS      arch/arm64/lib/memcpy.o
>   AS      arch/arm64/lib/memmove.o
>   AS      arch/arm64/lib/memset.o
>   AS      arch/arm64/lib/strchr.o
>   AS      arch/arm64/lib/strcmp.o
>   AS      arch/arm64/lib/strlen.o
>   AS      arch/arm64/lib/strncmp.o
>   AS      arch/arm64/lib/strnlen.o
>   AS      arch/arm64/lib/strrchr.o
>   AS      arch/arm64/lib/tishift.o
>   AR      arch/arm64/lib/lib.a
>   EXPORTS arch/arm64/lib/lib-ksyms.o
>   AR      arch/arm64/lib/built-in.o
> make[1]: Leaving directory '/root/r/out'
> Makefile:146: recipe for target 'sub-make' failed
> make: *** [sub-make] Error 2
> ```

Revert https://github.com/Panchajanya1999/msm-4.14/commit/29eed7e275c242821ea40eff587ea218cd420039

**Comment by zixijian** [comment]
Revert can be compiled normally.

**Comment by Panchajanya1999** [comment]
> Revert can be compiled normally.

source fixed totally now.
