### ISSUE TITLE
violet can't boot

### ISSUE THREAD

**Issue by zixijian** [Panchajanya1999/msm-4.14#9]
Since I compiled a kernel in April, I can't boot using the new kernel in May.

**Comment by Panchajanya1999** [comment]
what exactly you did?

**Comment by zixijian** [comment]
The latest version MIUI I use, and did not change the kernel.

**Comment by Panchajanya1999** [comment]
Miui issue maybe.

**Comment by zixijian** [comment]
Maybe I should use AOSP ROM.
